name: Action

on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '.gitattributes'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
  pull_request:
    branches:
      - master
      - main
    paths-ignore:
      - '.gitattributes'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  action:
    name: Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Config Git
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Action
        run: python script/main.py
      - name: Update Submodule
        run: |
          git submodule sync
          git submodule update --init --recursive
          git submodule update --remote
          if [[ `git status --porcelain` ]]; then
            git add .
            git commit -m "Auto Update"
            git push
          else
            echo pass
          fi
